version: "3.9"

services:
  api:
    build:
      context: .
    container_name: server
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: secret

  database:
    image: postgres:12-alpine
    container_name: backend_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
